### PR TITLE
Split from_gatt and to_gatt into separate traits and implement for &'static str

### LINKED ISSUE #272: Impl of FixedGattValue for &str seems wrong
I was attempting to send a string as a characteristic with the following code:
```rust
#[gatt_service(uuid = DEVICE_INFO_SERVICE_UUID)]
struct DeviceInfoService {
    #[characteristic(uuid = "00002a25-0000-1000-8000-00805f9b34fb", value = "1337", read)]
    serial_number: &'static str,
}
```

I could see the characteristic but it had an odd nonsense value that was not valid utf8

Looking at the code for the `impl<T: Primitive> FixedGattValue for T` it seems that `SIZE` is set as ` mem::size_of::<Self>();`  and in the case of `T = &str`  this wont actually be the size of the str slice, just the size of the reference.

Having realized this I switched to trying to use `heapless::String` (as shown below) and that worked as expected. 

```rust
#[gatt_service(uuid = DEVICE_INFO_SERVICE_UUID)]
struct DeviceInfoService {
    #[characteristic(uuid = "00002a25-0000-1000-8000-00805f9b34fb", value = heapless::String::from_str("1337").unwrap(), read)]
    serial_number: heapless::String<8>,
}
```

### PR DESCRIPTION
**Pull request by petekubiak**
The implementation of `GattValue` for `&'_ str` was incorrect, and was returning the reference's memory on the stack rather than the slice it was pointing to. Furthermore, there were issues linking lifetimes of references as gatt values to their &[u8] equivalent (see #272 for more details)

This PR splits `GattValue` into separate traits `FromGatt` and `ToGatt` where `FromGatt` requires that `ToGatt` is implemented. This allows us to implement `to_gatt` on `&'static str` and other static references without having to implement `from_gatt`, which would potentially be unsafe.

Fixes #272.

### CODE REVIEW

**Comment by jamessizeland** [comment]
Just a thought, should the trait be IntoGatt rather than ToGatt? I'm not sure which is more idiomatic.

File: host/src/lib.rs [hunk 1]
```diff
@@ -97,7 +97,7 @@ pub mod prelude {
     #[cfg(feature = "scan")]
     pub use crate::scan::*;
     #[cfg(feature = "gatt")]
-    pub use crate::types::gatt_traits::{FixedGattValue, GattValue};
```
Comment (jamessizeland) [inline host/src/lib.rs:100]: We're no longer exposing the traits in the prelude, is this the plan?

**Comment by petekubiak** [comment]
I wondered this, and then thought that if the trait was called IntoGatt, the function should also be called into_gatt...

File: host/src/lib.rs (hunk 1 above)
Comment (petekubiak) [reply host/src/lib.rs:100]: Nope! That was me on autopilot xD

**Comment by jscatena88** [comment]
In reference to the trait names there is potentially an argument to be made that it should be `AsGatt` if we think the conversions will always be fairly cheap. `To` implies that is an expensive/slow conversion: https://rust-lang.github.io/api-guidelines/naming.html#ad-hoc-conversions-follow-as_-to_-into_-conventions-c-conv

This is a nit though so don't feel obligated at all

File: host/src/types/gatt_traits.rs [hunk 2]
```diff
@@ -138,22 +143,38 @@ impl<const N: usize> GattValue for [u8; N] {
...
 }
+
+impl ToGatt for &'static str {
+    const MIN_SIZE: usize = 0;
+    const MAX_SIZE: usize = usize::MAX;
+
+    fn to_gatt(&self) -> &[u8] {
+        self.as_bytes()
+    }
+}
```
Comment (jscatena88) [inline host/src/types/gatt_traits.rs:180]: Does this have to be static? I'd imagine almost any use case would have it be static but I wonder if you can get a little extra flexibility by using a generic lifetime. This should work the same for a &`static str I believe while also allowing non-static `&str`s to be used assuming the borrow checker agrees.

```suggestion
impl<'a> ToGatt for &'a str {
    const MIN_SIZE: usize = 0;
    const MAX_SIZE: usize = usize::MAX;

    fn to_gatt(&self) -> &'a [u8] {
        self.as_bytes()
    }
}
```

**Comment by jscatena88** [comment]
Overall looks like a great improvement! I don't have time at this exact moment to test on HW or on the project I was working on but I see no reason it wouldn't all work

**Review by jscatena88 — APPROVED** [review]

File: host/src/types/gatt_traits.rs (hunk 2 above)
Comment (lulf) [reply host/src/types/gatt_traits.rs:180]: See the discussion here https://github.com/embassy-rs/trouble/issues/272 @jscatena88

**Review by lulf — APPROVED** [review]
Thanks for fixing this, looks great!

**Comment by petekubiak** [comment]
Just to mention, I'm fully on board with moving to AsGatt instead, I think there's a strong argument there. I'll raise a PR for it.

File: host/src/types/gatt_traits.rs (hunk 2 above)
Comment (jscatena88) [reply host/src/types/gatt_traits.rs:180]: It looks like the complications there were from implementing `from_gatt` not `to_gatt`. I'm still somewhat confident that the code I wrote above should work actually. It is passing tests locally on my laptop (except for one test that seems to be expecting connected hardware? `gatt_client_server`). But either way not a big deal
